Alert description
plexsystems/promdoc pull request #9
Opened 2020-09-01 14:26 UTC by nlamirault

Some monitoring-mixins have annotations : description, summary, message, ...

Generated markdown : 

# Alerts

## Rule Groups

* [AlertmanagerAlerts](#AlertmanagerAlerts)
* [ElasticsearchAlerts](#ElasticsearchAlerts)
* [MysqlAlerts](#MysqlAlerts)
* [RabbitMQAlerts](#RabbitMQAlerts)
* [RedisAlerts](#RedisAlerts)
* [VarnishAlerts](#VarnishAlerts)
* [deadmansswitch](#deadmansswitch)
* [etcd](#etcd)
* [kube-apiserver-slos](#kube-apiserver-slos)
* [kube-prometheus-node-alerting](#kube-prometheus-node-alerting)
* [kubernetes-absent](#kubernetes-absent)
* [kubernetes-apps](#kubernetes-apps)
* [kubernetes-resources](#kubernetes-resources)
* [kubernetes-storage](#kubernetes-storage)
* [kubernetes-system](#kubernetes-system)
* [kubernetes-system-apiserver](#kubernetes-system-apiserver)
* [kubernetes-system-controller-manager](#kubernetes-system-controller-manager)
* [kubernetes-system-kubelet](#kubernetes-system-kubelet)
* [kubernetes-system-scheduler](#kubernetes-system-scheduler)
* [logging_elasticsearch.alerts](#logging_elasticsearch.alerts)
* [loki_alerts](#loki_alerts)
* [node-disk](#node-disk)
* [node-exporter](#node-exporter)
* [node-network](#node-network)
* [node_exporter](#node_exporter)
* [prometheus](#prometheus)
* [promtail_alerts](#promtail_alerts)
* [sk5_node](#sk5_node)
* [thanos-bucket-replicate.rules](#thanos-bucket-replicate.rules)
* [thanos-compact.rules](#thanos-compact.rules)
* [thanos-component-absent.rules](#thanos-component-absent.rules)
* [thanos-query.rules](#thanos-query.rules)
* [thanos-receive.rules](#thanos-receive.rules)
* [thanos-rule.rules](#thanos-rule.rules)
* [thanos-sidecar.rules](#thanos-sidecar.rules)
* [thanos-store.rules](#thanos-store.rules)

## AlertmanagerAlerts

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|AlertmanagerConfigurationReload|AlertManager configuration reload (instance {{ $labels.instance }})|AlertManager configuration reload error   VALUE = {{ $value }}   LABELS: {{ $labels }}|warning|
|AlertmanagerNotificationsFailing|Alertmanager is seeing errors for integration {{$labels.integration}}|Alertmanager is seeing errors for integration {{$labels.integration}}|critical|

## ElasticsearchAlerts

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|ElasticHeapUsageTooHigh|Elastic Heap Usage Too High (instance {{ $labels.instance }})||warning|
|ElasticHeapUsageWarning|Elastic Heap Usage warning (instance {{ $labels.instance }})||warning|
|ElasticClusterRed|Elastic Cluster Red (instance {{ $labels.instance }})||warning|
|NumberOfElasticHealthyNodes|Number of Elastic Healthy Nodes (instance {{ $labels.instance }})||warning|
|NumberOfElasticHealthyDataNodes|Number of Elastic Healthy Data Nodes (instance {{ $labels.instance }})||warning|
|NumberOfRelocationShards|Number of relocation shards (instance {{ $labels.instance }})||warning|
|NumberOfInitializingShards|Number of initializing shards (instance {{ $labels.instance }})||warning|
|NumberOfUnassignedShards|Number of unassigned shards (instance {{ $labels.instance }})||warning|
|NumberOfPendingTasks|Number of pending tasks (instance {{ $labels.instance }})||warning|
|ElasticNoNewDocuments|Elastic no new documents (instance {{ $labels.instance }})||warning|

## MysqlAlerts

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|MysqlDown|MySQL down (instance {{ $labels.instance }})||critical|
|OpenFilesHigh|Instance {{ $labels.instance }} open files high||warning|
|ReadBufferSizeTooBig|Instance {{ $labels.instance }} Read buffer size is bigger than max. allowed packet size||warning|
|SortBufferMissconfigured|Instance {{ $labels.instance }} Sort buffer possibly missconfigured||warning|
|ThreadStackSizeTooSmall|Instance {{ $labels.instance }} Thread stack size is too small||warning|
|MaxConnectionsLimited|Instance {{ $labels.instance }} Used more than 80% of max connections limited||warning|
|InnoDBForceRecovery|Instance {{ $labels.instance }} InnoDB Force Recovery is enabled||warning|
|InnoDBLogFileSizeTooSmall|Instance {{ $labels.instance }} InnoDB Log File size is too small||warning|
|InnoDBFlushLogTransactionCommit|Instance {{ $labels.instance }} InnoDB Flush Log at Transaction Commit||warning|
|TableDefinitionCacheTooSmall|Instance {{ $labels.instance }} Table definition cache too small||low|
|TableOpenCacheTooSmall|Instance {{ $labels.instance }} Table open cache too small||low|
|ThreadStackSizeTooSmall|Instance {{ $labels.instance }} Thread stack size is possibly too small||low|
|InnoDBBufferPoolInstancesTooSmall|Instance {{ $labels.instance }} InnoDB Buffer Pool Instances is too small||low|
|InnoDBPlugin|Instance {{ $labels.instance }} InnoDB Plugin is enabled||low|
|BinaryLogDisabled|Instance {{ $labels.instance }} Binary Log is disabled||warning|
|BinlogCacheSizeTooSmall|Instance {{ $labels.instance }} Binlog Cache size too small||low|
|BinlogStatementCacheSizeTooSmall|Instance {{ $labels.instance }} Binlog Statement Cache size too small||low|
|BinlogTransactionCacheSizeTooSmall|Instance {{ $labels.instance }} Binlog Transaction Cache size too small||low|
|SyncBinlog|Instance {{ $labels.instance }} Sync Binlog is enabled||low|
|IOThreadStopped|Instance {{ $labels.instance }} IO thread stopped||critical|
|SQLThreadStopped|Instance {{ $labels.instance }} SQL thread stopped||critical|
|SQLThreadStopped|Instance {{ $labels.instance }} Sync Binlog is enabled||critical|
|SlaveLaggingBehindMaster|Instance {{ $labels.instance }} Slave lagging behind Master||warning|
|SlaveNotReady|Instance {{ $labels.instance }} Slave is NOT read only||low|

## RabbitMQAlerts

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|RabbitmqDown|Rabbitmq down (instance {{ $labels.instance }})||critical|
|ClusterPartition|Cluster partition (instance {{ $labels.instance }})||warning|
|TooManyConnections|Too many connections (instance {{ $labels.instance }})||warning|
|OutOfMemory|Out of memory (instance {{ $labels.instance }})||warning|
|DeadLetterQueueFillingUp|Dead letter queue filling up (instance {{ $labels.instance }})||warning|
|TooManyMessagesInQueue|Too many messages in queue (instance {{ $labels.instance }})||warning|
|SlowQueueConsuming|Slow queue consuming (instance {{ $labels.instance }})||warning|

## RedisAlerts

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|RedisDown|Redis down (instance {{ $labels.instance }})||critical|
|OutOfMemory|Out of memory (instance {{ $labels.instance }})||warning|
|ReplicationBroken|Replication broken (instance {{ $labels.instance }})||warning|
|TooManyConnections|Too many connections (instance {{ $labels.instance }})||warning|
|NotEnoughConnections|Not enough connections (instance {{ $labels.instance }})||warning|
|RejectedConnections|Rejected connections (instance {{ $labels.instance }})||warning|

## VarnishAlerts

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|VarnishDown|Varnish {{ $labels.instance }} is currently down||critical|

## deadmansswitch

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|DeadMansSwitch|This is a DeadMansSwitch meant to ensure that the entire Alerting pipeline is functional.||critical|

## etcd

|Name|Summary|Description|Severity|Runbook|
|---|---|---|---|---|
|etcdMembersDown|etcd cluster "{{ $labels.job }}": members are down ({{ $value }}).||critical|
|etcdInsufficientMembers|etcd cluster "{{ $labels.job }}": insufficient members ({{ $value }}).||critical|
|etcdNoLeader|etcd cluster "{{ $labels.job }}": member {{ $labels.instance }} has no leader.||critical|
|etcdHighNumberOfLeaderChanges|etcd cluster "{{ $labels.job }}": {{ $value }} leader changes within the last 15 minutes. Frequent elections may be a sign of insufficient resources, high network latency, or disruptions by other components and should be investigated.||warning|
|etcdHighNumberOfFailedGRPCRequests|etcd cluster "{{ $labels.job }}": {{ $value }}% of requests for {{ $labels.grpc_method }} failed on etcd instance {{ $labels.in [...]

2020-09-02 19:47 UTC, jpreese commented
Thanks for putting this together @nlamirault! This makes sense to me.

Just a couple small nits from the review bot and we'll get this merged in.

2020-09-02 19:52 UTC, jpreese requested changes
There are a couple nits from the review bot--unused methods.

2020-09-03 06:41 UTC, nlamirault commented
I update the code.

2020-09-04 22:35 UTC, jpreese approved these changes
LGTM! 🎉

2020-09-04 22:35 UTC, merged